# Meta Data for SEO

## Homepage
title = "DBKover"
titleSeparator = "-"
titleAddition = "Database testing made easy"
description = "DBKover is a library to enable easy integration testing to databases using DBUnit."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "dbkover.io"
titleHome = "Doks Theme"

## Twitter Cards
#twitterSite = "@getdoks"
#twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "DBKover"
#schemaAuthor = "Henk Verlinde"
#schemaAuthorTwitter = "https://twitter.com/henkverlinde"
#schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
#schemaAuthorGitHub = "https://github.com/dbkover/dbkover"
schemaLocale = "en-US"
#schemaLogo = "logo-doks.png"
#schemaLogoWidth = 512
#schemaLogoHeight = 512
#schemaImage = "doks.png"
#schemaImageWidth = 1280
#schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/dbkover/dbkover"
#schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = ""

# Feed
copyRight = ""

# Alert
alert = false
alertDismissable = true
alertText = ""

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/dbkover/dbkover"
docsRepoBranch = "main"
docsRepoSubPath = "docs"
editPage = true
lastMod = true

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
