name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
  SONATYPE_BASE_URL: https://s01.oss.sonatype.org/service/local/

jobs:
  sonatype-create-repository:
    runs-on: ubuntu-latest
    name: Create SonaType repository
    outputs:
      repository-id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        name: Create SonaType repository
        uses: nexus-actions/create-nexus-staging-repo@v1.1
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          base_url: ${{ env.SONATYPE_BASE_URL }}
          description: Created by Release (Create SonaType repository) for '${{ github.ref }}'

  publish:
    runs-on: ubuntu-latest
    needs:
      - sonatype-create-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish project
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishAllPublicationsToSonatypeRepository
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.sonatype-create-repository.outputs.repository-id }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

  finalize:
    runs-on: ubuntu-latest
    needs:
      - sonatype-create-repository
      - publish
    if: ${{ always() && needs.sonatype-create-repository.result == 'success' }}
    steps:
      - name: Discard
        if: ${{ needs.publish.result != 'success' }}
        uses: nexus-actions/drop-nexus-staging-repo@v1
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.sonatype-create-repository.outputs.repository-id }}
          base_url: ${{ env.SONATYPE_BASE_URL }}

      - name: Release
        if: ${{ needs.publish.result == 'success' }}
        uses: nexus-actions/release-nexus-staging-repo@v1.2
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.sonatype-create-repository.outputs.repository-id }}
          base_url: ${{ env.SONATYPE_BASE_URL }}

  release:
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
